version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: testdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '8000:8000'
    environment:
      DB_URL: 'postgresql://fastapi:secret@db:5432/testdb'
    depends_on:
      - db

volumes:
  postgres_data:
