name: Deploy to ECS

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REPO: 323612677378.dkr.ecr.us-east-1.amazonaws.com/fastapi-crud
  ECS_CLUSTER: fastapi-cluster
  ECS_SERVICE: fastapi-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: fastapi_crud_secrets_for_aws

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Secrets
        run: |
          echo "AWS_ACCESS_KEY_ID exists: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
          echo "AWS_SECRET_ACCESS_KEY exists: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to ECR
        run: |
          set -e
          echo "Building Docker image..."
          docker build -t $ECR_REPO:latest .
          docker tag $ECR_REPO:latest $ECR_REPO:${{ github.sha }}
          echo "Pushing both latest and commit-tagged images to ECR..."
          docker push $ECR_REPO:latest
          docker push $ECR_REPO:${{ github.sha }}

      - name: Force new ECS deployment
        run: |
          set -e
          echo "Triggering ECS deployment..."
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment \
            --region $AWS_REGION
